### ISSUE TITLE
The Ci_query_log don´t save operations logs in action UPDATE, DELETE, INSERT 

### ISSUE THREAD

**Issue by denisVitonis** [ozanmora/ci_log_query#1]
Hi ozanmora
First congratulations on the creation of HOOK.
I implanted in my system this hook and it worked perfectly, but the actions of UPDATE, INSERT and DELETE are not recorded in the log file.

Is it something of a config in Codeigniter?

See u  ozanmora

**Comment by ozanmora** [comment]
Hello @denisVitonis ,

I noticed the same problem. I have no idea where exactly the reason. But I am thinking of updating this code. When I solve the issue, I will note here.

If you can find a solution to this issue, I would be glad if you can share it with me.

Thanks

**Comment by denisVitonis** [comment]
Dear Ozan, I managed to solve it in another way, however using your hook.
First and I created a helper.
with the function
////////////**********CODE IN helper FILE*************//////////////////////////
function log_queries_2($sql) {
        $filepath = APPPATH . 'logs/Query-log-' . date('Y-m-d') . '.php';   
            $handle = fopen($filepath, "a+");
            fwrite($handle, $sql." \n Execution Time: ".date("Y-m-d H:i:s")."\n\n");  
            fclose($handle);   
}
//////////////**************************///////////////////
After this go to system/database/DB_driver.php and find function named "query" and put this below code on top inside the function.
It may not be the best of good practices but it works perfectly.

////////////**********CODE IN DB_driver.php  FILE*************//////////////////////////
log_queries_2($sql);'

//////////////**************************///////////////////

**Comment by ozanmora** [comment]
> Dear Ozan, I managed to solve it in another way, however using your hook.
> First and I created a helper.
> with the function
> ////////////**********CODE IN helper FILE*************//////////////////////////
> function log_queries_2($sql) {
> $filepath = APPPATH . 'logs/Query-log-' . date('Y-m-d') . '.php';
> $handle = fopen($filepath, "a+");
> fwrite($handle, $sql." \n Execution Time: ".date("Y-m-d H:i:s")."\n\n");
> fclose($handle);
> }
> //////////////**************************///////////////////
> After this go to system/database/DB_driver.php and find function named "query" and put this below code on top inside the function.
> It may not be the best of good practices but it works perfectly.
> 
> ////////////**********CODE IN DB_driver.php FILE*************//////////////////////////
> log_queries_2($sql);'
> 
> //////////////**************************///////////////////

this solution is not the right approach. Because if you want to be able to update Codeigniter, you should never make changes under the system folder.

I have made some code fixes but this problem is still not resolved.

I'm still investigating this problem. If I can find a solution, I want to update it as soon as possible.

**Comment by ozanmora** [comment]
I solved this problem. Actually, this was not an error. 

The code runs correctly and actually writes **INSERT**, **UPDATE**, **DELETE** queries to the log file.

However, this code only works on "**post_controller**" (Called immediately after your controller is fully executed). You can read the details of this from the [link](http://codeigniter.com/userguide3/general/hooks.html?highlight=post_controller).

You are probably doing a **redirect** after doing **INSERT**, **UPDATE**, **DELETE** operations like me. The controller cannot be completed if it contains redirecting. No database queries can be written to the log file because the operation could not be completed.

**P.S.:** My English is not very good. I apologize for this.
